### ISSUE TITLE
ipython notebook

### ISSUE THREAD

**Issue by willwang8129** [ccwang002/asia_lyrics#4]
執行 ipython notebook 的時候沒有自行打開網頁
好像找不到瀏覽器？

系統訊息如下
[W 22:25:09.455 NotebookApp] No web browser found: could not locate runnable browser.

**Comment by ccwang002** [comment]
你是在工作站上面跑嗎？表示你的電腦找不到瀏覽器

**Comment by ccwang002** [comment]
不過有個解法是預設會開在 http://localhost:8888 你可以自己在同機器打開瀏覽器去訪問這個網址。

如果是工作站的話，只聽 localhost 外面的機器沒有辦法訪問，你可以把開啟的指令改成

``` sh
ipython notebook --ip="*"
```

就要就會聽全部 ip 了，由於他預設是開在 port 8888，外面機器如果連不上的話，可能是被防火牆檔到了

**Comment by willwang8129** [comment]
對唷 我是在工作站上面跑 所以那邊執行的指令沒辦法透過我自己的電腦瀏覽器開起來囉？

**Comment by willwang8129** [comment]
我用 ipython notebook --ip="*" 結果多了兩個錯誤XD

[W 22:39:05.751 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 22:39:05.751 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.

**Comment by willwang8129** [comment]
應該是警告XD

**Comment by ccwang002** [comment]
恩因為等於開了一個 web shell 在 public ip 上面，任何人有這個網址就可以做 remote execution。這是安全性的考量，並不會影響程式的運行。如果你覺得不放心的話，我自己在 server 上有加開 https 與密碼，官網有操作說明。

**Comment by willwang8129** [comment]
可是用剛剛那個指令好像還是沒辦法開啟網頁

**Comment by ccwang002** [comment]
那我詳細說明一下好了，IPython Notebook 的原理就是在機器上開一個 web server 然後去把 notebook 文件 render 成 HTML 以及跟實際的 Python shell 溝通。

假如你的 server ip 是 `<server-ip>`，那平常用 SSH 登入 server 可能就是用

``` sh
ssh id@<server-ip>
```

所以同理如果 notebook server 執行的時候，他預設是用 8888 port，這時候在自己的電腦的 browser 上打 http://<server-ip>:8888 應該能看到。

如果上面的流程都做了，但還是看不到網頁的話，一般來說是防火牆的問題，因為不是每台 server 都會打開 8888 port，你可以用以下方法來檢測，在同一個目錄底下，

``` sh
$ python3 -m http.server 8888
Serving HTTP on 0.0.0.0 port 8888 ...
```

0.0.0.0 表示所有的 ip 位址都聽，那這樣就會包含  `<server-ip>`。這時候訪問 http://<server-ip>:8888 應該要能看到該目錄底下的檔案。如果這時候還是沒畫面的話，可以肯定是被防火牆擋掉了。這邊就要看 server 是怎麼設定的，能不能請網管修改，或問他(她)有哪個 port 是開放的。

如果有畫面的話就表示是 ipython notebook 的問題，到時候再把錯誤訊息給我看吧。

**Comment by willwang8129** [comment]
應該是沒問題囉!! 有順利開起來
因為我用windows的關係 找了很久才找到port forwarding的方法 :)

**Comment by ccwang002** [comment]
Good. Then I'll close this :)
